In [4]:
import numpy as np
a=[10,20,30,50]
b=np.asarray(a,dtype=float)
print(b)

[10. 20. 30. 50.]


In [5]:
a=np.array([[10,20,40],[50,60,70]])
print(a)

[[10 20 40]
 [50 60 70]]


In [11]:
a[0][1]

20

In [16]:
a=np.array([[[10,20,30],[40,50,60]],[[60,70,80],[90,34,56]]])
print(a)

[[[10 20 30]
  [40 50 60]]

 [[60 70 80]
  [90 34 56]]]


In [17]:
a[1][1][0]

90

In [18]:
a[0][1][1]

50

In [19]:
a=np.array([[10,20,40],[50,60,70]])
b=np.asarray(a,order="C")#row wise accesing
print(b)

[[10 20 40]
 [50 60 70]]


In [20]:
for i in np.nditer(b):
    print(i)

10
20
40
50
60
70


In [21]:
a=np.array([[10,20,40],[50,60,70]])
b=np.asarray(a,order="F")#column wise accesing
print(b)

[[10 20 40]
 [50 60 70]]


In [22]:
for i in np.nditer(b):
    print(i)

10
50
20
60
40
70


In [28]:
a=b"welcome"
b=np.frombuffer(a,dtype="S1",count=4,offset=1)
print(b)

[b'e' b'l' b'c' b'o']


In [29]:
a=[10,20,30]
b=np.fromiter(a,dtype="int")
b

array([10, 20, 30])

In [30]:
b=np.fromiter(a,dtype="S1")
b

array([b'1', b'2', b'3'], dtype='|S1')

In [35]:
np.zeros([2,3])

array([[0., 0., 0.],
       [0., 0., 0.]])

In [36]:
np.full([2,3],1)

array([[1, 1, 1],
       [1, 1, 1]])

In [38]:
np.random.rand(2,3)

array([[0.33983287, 0.28767517, 0.86984063],
       [0.6846208 , 0.92316567, 0.9975911 ]])

In [39]:
np.ones([2,3])

array([[1., 1., 1.],
       [1., 1., 1.]])

In [40]:
np.eye(5)#diagonal elements 1 remaining all are zeroes

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [3]:
a=np.arange(10,20,2)#start:stop:step
print(a)

NameError: name 'np' is not defined

In [44]:
a.reshape(5,1)

array([[10],
       [12],
       [14],
       [16],
       [18]])

In [45]:
a.reshape(1,5)

array([[10, 12, 14, 16, 18]])

In [48]:
a=np.linspace(10,20,2,endpoint=False,retstep=True)#here 2 means 2 equal parts
a

(array([10., 15.]), 5.0)

In [49]:
a

(array([10., 15.]), 5.0)

In [54]:
a=np.array([[10,20,30],[40,50,60]])
a

array([[10, 20, 30],
       [40, 50, 60]])

In [55]:
a.reshape(2,3)

array([[10, 20, 30],
       [40, 50, 60]])

In [56]:
a.reshape(3,2)

array([[10, 20],
       [30, 40],
       [50, 60]])

In [57]:
np.size(a)


6

In [58]:
np.shape(a)

(2, 3)

In [60]:
a.dtype

dtype('int32')

In [6]:
a[2:5]

array([], shape=(0, 3), dtype=int32)

In [7]:
m=np.arange(10,100,10)
m

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [63]:
m[3:8]

array([40, 50, 60, 70, 80])

In [64]:
n=np.copy(m)
print(n)

[10 20 30 40 50 60 70 80 90]


In [66]:
m,n

(array([10, 20, 30, 40, 50, 60, 70, 80, 90]),
 array([10, 20, 30, 40, 50, 60, 70, 80, 90]))

In [67]:
p=n.view()
p

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [68]:
n[6]=200
n

array([ 10,  20,  30,  40,  50,  60, 200,  80,  90])

In [69]:
p

array([ 10,  20,  30,  40,  50,  60, 200,  80,  90])

In [70]:
sort=np.sort(p)
sort

array([ 10,  20,  30,  40,  50,  60,  80,  90, 200])

In [8]:
p.reshape([3,3])
p



NameError: name 'p' is not defined

In [9]:
c=np.array([[70,20,30],[40,50,60]])
c

array([[70, 20, 30],
       [40, 50, 60]])

In [80]:
d=np.sort(c,axis=0)#column wise sorting
d

array([[40, 20, 30],
       [70, 50, 60]])

In [81]:
np.sort(c,axis=1)#row wise sorting #without1 by default axis=1

array([[20, 30, 70],
       [40, 50, 60]])

In [93]:
f=np.dtype([("name","S1"),("perc",float)])
g=np.array([("zaani",100.44),("raju",90.4)],dtype=f)
g

array([(b'z', 100.44), (b'r',  90.4 )],
      dtype=[('name', 'S1'), ('perc', '<f8')])

In [94]:
np.sort(g,order="name")

array([(b'r',  90.4 ), (b'z', 100.44)],
      dtype=[('name', 'S1'), ('perc', '<f8')])

In [96]:
np.sort(g,order="perc")

array([(b'r',  90.4 ), (b'z', 100.44)],
      dtype=[('name', 'S1'), ('perc', '<f8')])

In [98]:
a=np.array([10,20,40])
b=np.array([40,50,60])
c=np.append(a,b)
c

array([10, 20, 40, 40, 50, 60])

In [105]:
g=np.insert(a,3,[45,70])
g

array([10, 20, 40, 45, 70])

In [106]:
np.delete(g,4)

array([10, 20, 40, 45])

In [110]:
s=np.array([[10,20,40],[50,100,80]])
t=np.array([[50,60,70],[80,12,5]])
u=np.concatenate((s,t))

In [111]:
u

array([[ 10,  20,  40],
       [ 50, 100,  80],
       [ 50,  60,  70],
       [ 80,  12,   5]])

In [114]:
g=np.concatenate((s,t),axis=1)#row wise concatenation
g


array([[ 10,  20,  40,  50,  60,  70],
       [ 50, 100,  80,  80,  12,   5]])

In [118]:
g=np.concatenate((s,t),axis=0)#sorting coulm wise

In [119]:
g

array([[ 10,  20,  40],
       [ 50, 100,  80],
       [ 50,  60,  70],
       [ 80,  12,   5]])

In [117]:
s,t

(array([[ 10,  20,  40],
        [ 50, 100,  80]]), array([[50, 60, 70],
        [80, 12,  5]]))

In [120]:
f=np.stack((s,t))
f

array([[[ 10,  20,  40],
        [ 50, 100,  80]],

       [[ 50,  60,  70],
        [ 80,  12,   5]]])

In [122]:
f[0]

array([[ 10,  20,  40],
       [ 50, 100,  80]])

In [123]:
g=np.stack((s,t),axis=1)
g

array([[[ 10,  20,  40],
        [ 50,  60,  70]],

       [[ 50, 100,  80],
        [ 80,  12,   5]]])

In [124]:
s,t

(array([[ 10,  20,  40],
        [ 50, 100,  80]]), array([[50, 60, 70],
        [80, 12,  5]]))

In [125]:
h=np.stack((s,t),axis=0)
h

array([[[ 10,  20,  40],
        [ 50, 100,  80]],

       [[ 50,  60,  70],
        [ 80,  12,   5]]])

In [127]:
 i=np.vstack((s,t))#column wise axis=0 while concatneation
 i   

array([[ 10,  20,  40],
       [ 50, 100,  80],
       [ 50,  60,  70],
       [ 80,  12,   5]])

In [130]:
j=np.hstack((s,t))#row wise axis=1 while concatneation
j

array([[ 10,  20,  40,  50,  60,  70],
       [ 50, 100,  80,  80,  12,   5]])

In [131]:
k=np.dstack((s,t))
k

array([[[ 10,  50],
        [ 20,  60],
        [ 40,  70]],

       [[ 50,  80],
        [100,  12],
        [ 80,   5]]])

In [134]:
s=np.arange(10,150,10)
s

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120, 130,
       140])

In [137]:
t=np.split(s,2)
t

[array([10, 20, 30, 40, 50, 60, 70]),
 array([ 80,  90, 100, 110, 120, 130, 140])]

In [138]:
s1,s2=t

In [139]:
s1

array([10, 20, 30, 40, 50, 60, 70])

In [140]:
s2

array([ 80,  90, 100, 110, 120, 130, 140])

In [154]:
b=np.array([10,20])
c=np.where(b==70)
b

array([10, 20])

In [151]:
c

(array([0], dtype=int64), array([2], dtype=int64))

In [155]:
b

array([10, 20])

In [156]:
f=np.searchsorted(b,20)
f

1

In [163]:
g=np.array([[10,24,40],[40,50,60]])
f=g=np.array([[10,20,40],[70,50,60]])
g


array([[10, 20, 40],
       [70, 50, 60]])

In [162]:
f

array([[10, 20, 40],
       [70, 50, 60]])

In [164]:
g=np.array([[10,20,40],[50,60,69]])
g

array([[10, 20, 40],
       [50, 60, 69]])

In [165]:
h=np.array([[30,4,0],[4,5,6]])
h

array([[30,  4,  0],
       [ 4,  5,  6]])

In [166]:
i=np.add(g,h)
i

array([[40, 24, 40],
       [54, 65, 75]])

In [167]:
j=np.subtract(g,h)
j

array([[-20,  16,  40],
       [ 46,  55,  63]])

In [168]:
k=np.multiply(g,h)
k

array([[300,  80,   0],
       [200, 300, 414]])

In [170]:
l=np.divide(g,h)
l

C:\Users\MANi BABU\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[ 0.33333333,  5.        ,         inf],
       [12.5       , 12.        , 11.5       ]])

In [171]:
m=np.exp(g)
m

array([[2.20264658e+04, 4.85165195e+08, 2.35385267e+17],
       [5.18470553e+21, 1.14200739e+26, 9.25378173e+29]])

In [172]:
n=np.exp(h)
n

array([[1.06864746e+13, 5.45981500e+01, 1.00000000e+00],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02]])

In [173]:
g,h


(array([[10, 20, 40],
        [50, 60, 69]]), array([[30,  4,  0],
        [ 4,  5,  6]]))

In [174]:
h[1][0]=50
h[1][1]=60
h[1][2]=69
h

array([[30,  4,  0],
       [50, 60, 69]])

In [175]:
g==h


array([[False, False, False],
       [ True,  True,  True]])

In [176]:
np.array_equal(g,h)

False

In [178]:
k=np.min(g,axis=1)
k

array([10, 50])

In [179]:
l=np.max(g,axis=1)
l

array([40, 69])

In [180]:
k=np.sum(g,axis=1)
k

array([ 70, 179])